# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: .NET Build And Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        solution: [./src/DestinySandbox.sln]
        
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        check-latest: true
        # cache: 'npm'
        # cache-dependency-path: '**/package.lock.json'
    - run: npm install
    - run: npm test
    
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.solution }} --use-lock-file

    - name: Build
      run: dotnet build  ${{ matrix.solution }} --no-restore

    - name: Initialize Local Environment
      run: dotnet run --project ./src/InitEnvironment/InitEnvironment.csproj

    - name: Test
      run: dotnet test  ${{ matrix.solution }} --no-build --verbosity normal
