name: .NET Build And Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/DestinySandbox.sln
    - name: Build
      run: dotnet build  ./src/DestinySandbox.sln --no-restore
    - name: Test
      run: dotnet test  ./src/DestinySandbox.sln --no-build --verbosity normal
