# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: .NET Build And Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/DestinySandbox.sln --locked-mode

    - name: Build
      run: dotnet build  ./src/DestinySandbox.sln --no-restore

    - name: Initialize Local Environment
      run: dotnet run --project .\src\InitEnvironment\InitEnvironment.csproj

    - name: Test
      run: dotnet test  ./src/DestinySandbox.sln --no-build --verbosity normal
