# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
name: Deployment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/2 * * *' # Every 2 hours.

jobs:
  Init_Publish_Deploy:
    runs-on: ubuntu-latest

    env: # These variables are available to the entire job.
      SOLUTION: ./src/DestinySandbox.sln

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

###**************

    - name: Dotnet Restore Dependencies
      run: dotnet restore ./src/DestinySandbox.sln

    - name: Dotnet Build
      run: dotnet build  ${{ env.SOLUTION }} --no-restore

    - name: Dotnet Run Initialize Local Environment
      run: dotnet run --project ./src/InitEnvironment/InitEnvironment.csproj -- ${{ github.workspace }}/root

    - name: dotnet publish
      run: dotnet publish ./src/SandboxWeb/SandboxWeb.csproj  -o ${{ github.workspace }}/root  # -c Release

    - name: List files
      shell: pwsh
      run: |
        Get-ChildItem '${{ github.workspace }}/root' -Recurse -Force | Write-Host

    #- name: Upload artifact for deployment job
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: .net-app
    #    path: ${{ github.workspace }}/root
    #    retention-days: 1

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'D2WeaponReport'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EE9871C4B5CA43C4A27E18E0D106F33A }}
        package: ${{ github.workspace }}/root

#************************
  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  environment:
  #    name: 'production'
  #    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #  steps:
  #  - name: Download artifact from build job
  #    uses: actions/download-artifact@v2
  #    with:
  #      name: .net-app

  #  - name: Deploy to Azure Web App
  #    id: deploy-to-webapp
  #    uses: azure/webapps-deploy@v2
  #    with:
  #      app-name: 'D2WeaponReport'
  #      slot-name: 'Production'
  #      publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EE9871C4B5CA43C4A27E18E0D106F33A }}
  #      package: .
